services:
  jekyll:
    image: bretfisher/jekyll-serve:stable-20251215-2119a31
    volumes:
      - .:/site
    ports:
      - '4001:4001'
    command: bundle exec jekyll serve --config _config.yml,_config_docker.yml --host 0.0.0.0 --port 4001 --watch --force_polling
